### ISSUE TITLE
array.reshape for (1, x) (x, 1) shapes

### ISSUE THREAD

**Issue by loroka** [v923z/micropython-ulab#180]
Array `reshape` method does not behave as expected.

From exmaple in the doc 
```python
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]], dtype=np.uint8)
a.reshape(1, 16) # > array([1, 2, 3, ..., 14, 15, 16], dtype=uint8)
```
this output differs from numpy where the output is `array([[1, 2, 3, ..., 14, 15, 16]], ...)`
```python
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]], dtype=np.uint8)
a.reshape(16, 1) # > array([1, 2, 3, ..., 14, 15, 16], dtype=uint8)
```
this output is wrong as I would expect output to be:
```
array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]], dtype=uint8)
```
For other shapes such as (2,8) or (8,2) method behaves as expected.

I think this issue might be somehow related to  #26.

**Comment by v923z** [comment]
You are right, this is a consequence of what is mentioned in https://github.com/v923z/micropython-ulab/issues/26. There is no way to distinguish between a one-dimensional array, and a two-dimensional one with a single element. This, and a number of other related issues have been addressed and fixed in https://github.com/v923z/micropython-ulab/tree/tensor. Apart from a couple of minor glitches, the code is complete, but I still have to work on the documentation. I hope I can pull that off over the weekend. 

As such, I would close this issue.
