### ISSUE TITLE
`array.dtype` stub & docs

### ISSUE THREAD

**Issue by CallumJHays** [v923z/micropython-ulab#269]
Hello and thank you very much for your work on this project.

I think the `array.dtype` stub is missing from the pyi comments.
I've added it in locally so that I can continue to rely on the stubs, and will submit a pull request shortly.

Also, I think that the current `latest` docs for dtype are incorrect as it is stated to be a property whereas currently on master it is a regular method. I believe the docs are desired behaviour, mirroring the numpy api. This might be being worked on in [the numpy-scipy branch](https://github.com/v923z/micropython-ulab/blob/numpy-scipy) but I figured I'd ask just to be sure.

**Comment by v923z** [comment]
> I think the `array.dtype` stub is missing from the pyi comments.
> I've added it in locally so that I can continue to rely on the stubs, and will submit a pull request shortly.

Many thanks, I have merged your changes!

> 
> Also, I think that the current `latest` docs for dtype are incorrect as it is stated to be a property whereas currently on master it is a regular method. 

There is a pending PR at https://github.com/micropython/micropython/pull/5648. The problem is that properties cannot be implemented in C in the current version of `micropython`. As soon as the issue is resolved, `dtype`, and many other things will become properties in `ulab`.
