### ISSUE TITLE
.transpose() missing

### ISSUE THREAD

**Issue by lhargrove** [v923z/micropython-ulab#40]
I recently updated to version 0.32.0 and notices that the .transpose() function was not available. 
`
>>> a = np.zeros((5,3))
>>> a.shape
(5, 3)
>>> a.transpose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ndarray' object has no attribute 'transpose'
>>> a.transpose()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ndarray' object has no attribute 'transpose'
`

**Comment by v923z** [comment]
Thanks for reporting the issue. This was caused by our efforts to make micropython-ulab and circuitpython-ulab compatible. However, the main problem is how micropython itself resolves properties. I have already proposed a solution. I hope this will soon be solved upstream.

Till then, I have implemented a temporary fix. The downside is that properties won't work in micropython, so you have to call `a.shape` as a function `a.shape()`. I hope this is acceptable for now. 

I know that this is only a beauty plaster, but we are working on a permanent solution.
