### ISSUE TITLE
[BUG] Spectrogram is not like scipy's spectrogram?

### ISSUE THREAD

**Issue by jepler** [v923z/micropython-ulab#435]
```python
>>> import ulab
>>> ulab.__version__
'3.3.1-2D'
```

**To Reproduce**
Place the following in a file and run it with micropython & python3:
```python
try:
  from ulab import numpy as np
except ImportError:
  import numpy as np
  
try:
  from ulab.scipy.signal import spectrogram
except ImportError:
  from scipy.signal import spectrogram

data = np.array([1,2,1,4])
print(spectrogram(data))
```

However, the return types of the spectrogram functions are entirely different, and the values don't seem related in an obvious way.
```
$ python -Wignore yon2.py
(array([0.  , 0.25, 0.5 ]), array([2.]), array([[0.33333333],
       [3.33333333],
       [3.        ]]))
$ ./micropython-coverage yon2.py
array([8.0, 2.0, 4.0, 2.0], dtype=float64)
```

**Expected behavior**
I wanted to create a program that finds the spectrum of some signal and is compatible between scipy and ulab, but the interfaces don't seem to be the same.

**Additional context**
Add any other context that might help to locate the root of the problem.

**Comment by v923z** [comment]
So, if I understand the issue properly, the problem is that the meaning of `spectrogram` is different in `scipy`, and `ulab`. I have just searched for that, and it seems to me that `signal.welch` is the closest to what is needed here: https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.welch.html, or, perhaps, `matplotlib.mlab.psd`: https://www.kite.com/python/docs/matplotlib.mlab.psd

I see four possibilities for a fix; none is ideal:
1. we remove the `spectrogram` function; that re-establishes compatibility, but introduces RAM overhead for an operation that is almost always required. Frankly, I think the power spectrum is probably one of the most-used functions, and I am pretty sure that it is more useful than the FFT itself. 
1. we move the spectrogram function `utils`. That also re-established compatibility, but keeps the function. The downside is that it is not clear what should happen on a PC.
1. we rename/rework the current implementation, and introduce `welch` instead. I think `welch` and the current implementation of  `spectrogram` are identical, if you take a single (non-overlapping) signal segment.
1. we move the function to a new module, `mlab`, and re-brand it as `psd`. This might make sense, if there are other functions of the `mlab` module that would be beneficial. 

Unfortunately, both `welch`, and `psd` return a 2-tuple, where the first element is the array of frequencies. That unnecessarily eats into the RAM again. 

If `spectrogram` is moved to `utils`, the following workaround is possible

```python
try:
  from ulab import numpy as np
  from ulab.utils import spectrogram
  use_ulab = True
except ImportError:
  import numpy as np
  use_ulab = False

def power_density(signal): 
  if use_ulab:
    return spectrogram(signal)
  else:
    return np.abs(np.fft.fft(signal))
```

**Comment by jepler** [comment]
Indeed, I ended up suggesting this in a guide:
```python
try:
  from ulab import numpy as np
except ImportError:
  import numpy as np
  
try:
  from ulab.scipy.signal import spectrogram
except ImportError:
  def spectrogram(arr):
    return abs(np.fft.fft(arr))

data = np.array([1,2,1,4])
print(spectrogram(data))
```

**Comment by jepler** [comment]
since in circuitpython we discovered this after "beta" we will elect to leave this function at `ulab.scipy.signal.spectrogram` for the time being, but introducing a forward-compatible name would be desirable. Since it doesn't seem to directly correspond to anything in numpy or scipy, putting it outside of those two submodule names seems like the best bet, and those few people who need to switch between circuitpython and blinka can write code similar to the above.

**Comment by v923z** [comment]
Then would it be OK, if we introduced an alias in `utils` now, and removed the function from `scipy.signal` at a later time? This could also be pointed out in the manual.

**Comment by v923z** [comment]
@jepler @dhalbert @tannewt 

I would really like to resolve this issue. Here are the main points of the discussion so far.

1. The current name does not conform to `scipy`, and as such, is misleading.
2. There is no similar function in  `scipy` or `numpy`. [welch](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.welch.html) and [psd](https://www.kite.com/python/docs/matplotlib.mlab.psd) are somewhat related, but they return a tuple with the power spectrum, and a list of frequencies. These frequencies are mostly useless on a `microcontroller`, because in the absence of a plotting library, you usually plot in terms of display pixels, anyway, but the very fact of having to hold the list of frequencies requires extra RAM for an irrelevant piece of information.
3. We could completely remove the function, and use the `numpy` convention `abs(fft.fft(...))`, but that assumes complex support in the firmware (adds something like 30% extra to the ulab-related firmware size), and uses extra RAM, because the result of `fft.fft(...)`, a complex array, has to be returned. 
4. The cheapest solution is to re-brand the function as `utils.spectrogram` (I am open to suggestions, if a different name is preferred), and use Jeff's workaround for compatibility. This approach is frugal with RAM (because internally it overwrites the array that was used for the calculation of the FFT itself), and does not rely on the implementation of complex arrays. https://github.com/v923z/micropython-ulab/blob/8154accf1b22661376f4320226c4a1958569d45f/code/numpy/fft/fft_tools.c#L261-L269

For compatibility with `numpy`, here is Jeff's solution. We could add this to the [snippets](https://github.com/v923z/micropython-ulab/tree/master/snippets)

```
try:
  from ulab.scipy.signal import spectrogram
except ImportError:
  def spectrogram(arr):
    return abs(np.fft.fft(arr))
```

In any case, I would like to have a solution that satisfies all parties.
