### ISSUE TITLE
[FEATURE REQUEST]how to install this ulab package in a calculator like Casio fx-CG50

### ISSUE THREAD

**Issue by PandaJohnWick** [v923z/micropython-ulab#469]
**Describe the solution you'd like**
I already have microPython 1.9.4 in the calculator, how do I install this package in the calculator, especially since numpy is important for matrix operations?
**Additional context**
Add any other context about the feature request here.

**Comment by v923z** [comment]
@PandaJohnWick You can't just install `ulab`, you have to compile the firmware for the specific platform, because `ulab` is very tightly integrated into the firmware. I don't know how you compile that for the Casio, but here are the steps for some of the more standard chips: https://github.com/v923z/micropython-ulab#firmware. I would suggest raising the question on the Casio user forum, if there is such a thing.

**Comment by v923z** [comment]
Since this issue is not really relevant here, I am closing it.
